name: 02 - Workflow Events
on: 
  # push:
  # schedule:
  #   - cron: '24 9 * * *'
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: |
          echo event name is:" ${{ github.event_name }} "
      
