name: 05 - 1 - Event Filters and ACtivity Types
on:
  # pull_request: 
  #   types: [opened, synchronize]
  #   branches: [master]
  workflow_dispatch: 

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Running whenever a PR is opened or sync AND base branch is master"