name: 07 - Using Expression
run-name: 07 - Using Expressions | DEBUG - ${{ inputs.debug == true && 'ON' || 'OFF' }}
on:
  # push:
  workflow_dispatch: 
    inputs:
      debug:
        type: boolean
        default: false

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - if: inputs.debug == true
        name: "[debug] Print start-up data"
        run: |
          echo "Triggered by: ${{ github.event_name }}"
          echo "Branch: ${{ github.ref }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Runner OS: ${{ runner.os }}"
      - if: github.ref_name == 'master' && inputs.debug == true
        name: "[debug] Print when triggered from master branch"
        run: |
          echo "I was triggerd from master branch."
      - run: echo "Hello, world"

    